name: Deploy to AWS
on:
  push:
    branches:
      - main  # Trigger the pipeline on main branch push

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.4.0"  # Use your desired Terraform version

      # Install or Update AWS CLI
      - name: Install or Update AWS CLI
        run: |
          # Check if AWS CLI is installed, and update if necessary
          if ! command -v aws &> /dev/null
          then
            echo "AWS CLI not found, installing..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          else
            echo "AWS CLI found, updating..."
            # Update AWS CLI
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            cd aws
            sudo ./install
          fi

      # Configure AWS credentials (set these in GitHub Secrets)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}

  deploy-blue:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.4.0"

      # Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Apply Terraform to deploy the blue environment
      - name: Deploy Blue Environment
        run: terraform apply -auto-approve -var="environment=blue"

      # Fetch the public IP dynamically
      - name: Get Public IP of Blue Environment
        id: get_blue_ip
        run: |
          echo "PUBLIC_IP=$(terraform output -raw instance_public_ip)" >> $GITHUB_ENV

      # Fetch the Load Balancer DNS Name dynamically
      - name: Get Load Balancer DNS
        id: get_lb_dns
        run: |
          echo "LOAD_BALANCER_DNS=$(terraform output -raw load_balancer_dns)" >> $GITHUB_ENV

      # Verify blue deployment using the public IP
      - name: Verify Blue Deployment
        run: |
          curl -f http://${{ env.PUBLIC_IP }}/index.html  # Replace with actual endpoint for verification

  switch-to-green:
    runs-on: ubuntu-latest
    needs: deploy-blue
    if: success()  # Run this job only if the blue deployment was successful

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.4.0"

      # Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Apply Terraform to switch to green environment
      - name: Switch to Green Environment
        run: terraform apply -auto-approve -var="environment=green"

      # Fetch the public IP of the green environment dynamically
      - name: Get Public IP of Green Environment
        id: get_green_ip
        run: |
          echo "GREEN_PUBLIC_IP=$(terraform output -raw instance_public_ip)" >> $GITHUB_ENV

      # Fetch the Load Balancer DNS Name for Green
      - name: Get Load Balancer DNS for Green
        id: get_green_lb_dns
        run: |
          echo "GREEN_LOAD_BALANCER_DNS=$(terraform output -raw load_balancer_dns)" >> $GITHUB_ENV

      # Verify green deployment using the green environment's public IP
      - name: Verify Green Deployment
        run: |
          curl -f http://${{ env.GREEN_PUBLIC_IP }}/index.html  # Replace with actual endpoint for verification

  update-load-balancer:
    runs-on: ubuntu-latest
    needs: switch-to-green
    if: success()  # Run this job only if the green environment is successfully deployed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.4.0"

      # Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Apply Terraform to update load balancer to point to green environment
      - name: Update Load Balancer to Green
        run: terraform apply -auto-approve -var="switch_to_green=true"

      # Optionally, add a health check or verification here to ensure that traffic is routed correctly
      - name: Verify Load Balancer Update
        run: |
          curl -f http://${{ env.GREEN_LOAD_BALANCER_DNS }}/index.html  # Check if the load balancer is routing traffic to the green environment
